import os
import json
import argparse
import logging
from typing import Dict, List, Optional, Tuple

# Reuse the existing OpenAI chat wrapper
try:
    from src.eval_utils_gpt_aeqa_qwen import call_openai_api
except ImportError:
    # Fallback for testing without openai dependency
    def call_openai_api(sys_prompt, contents, seed=None):
        logging.warning("OpenAI API not available, returning mock response")
        return "Mock caption response for testing purposes. This is a placeholder caption that would normally be generated by the AI model."


def _load_tuple_node(exp_tuple_path: str, question_id: str) -> Optional[dict]:
    """
    Load the question node for a given question_id from an exp_tuple json file.
    Compatible with two structures:
      1) Top-level mapping: { question_id: {"question": str, "step_0": {...}, ...} }
      2) Top-level episodes: { episode_key: { question_id: {"question": str, "steps": {...}} } }
    """
    if not exp_tuple_path or not os.path.exists(exp_tuple_path):
        logging.warning(f"exp_tuple file not found: {exp_tuple_path}")
        return None
    try:
        with open(exp_tuple_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        logging.error(f"failed to read exp_tuple: {e}")
        return None

    if not isinstance(data, dict):
        return None

    # Structure 1
    if question_id in data and isinstance(data[question_id], dict):
        return data[question_id]

    # Structure 2
    for _, bucket in data.items():
        if isinstance(bucket, dict) and question_id in bucket and isinstance(bucket[question_id], dict):
            return bucket[question_id]

    return None


def _collect_steps(qnode: dict) -> Tuple[str, List[Tuple[str, dict]]]:
    """
    Return the question text and a sorted list of (step_key, step_dict).
    Supports both scattered step_* and nested steps dict.
    """
    if not isinstance(qnode, dict):
        return "", []

    question_text = qnode.get("question", "")

    steps_obj = None
    if "steps" in qnode and isinstance(qnode["steps"], dict):
        steps_obj = qnode["steps"]
    else:
        steps_obj = {k: v for k, v in qnode.items() if isinstance(v, dict) and k.startswith("step_")}

    if not steps_obj:
        return question_text, []

    def _step_order(k: str) -> int:
        try:
            return int(k.split("_")[-1])
        except Exception:
            return 0

    items = sorted(list(steps_obj.items()), key=lambda kv: _step_order(kv[0]))
    return question_text, items


def _is_question_node(node: dict) -> bool:
    if not isinstance(node, dict):
        return False
    if not isinstance(node.get("question"), str):
        return False
    if isinstance(node.get("steps"), dict):
        return True
    for k, v in node.items():
        if isinstance(v, dict) and isinstance(k, str) and k.startswith("step_"):
            return True
    return False


def load_all_question_nodes(exp_tuple_path: str) -> Dict[str, dict]:
    """
    Load all question nodes from the tuple file, supporting both top-level qid and
    episode->qid layouts. Returns mapping {question_id: question_node}.
    """
    result: Dict[str, dict] = {}
    if not exp_tuple_path or not os.path.exists(exp_tuple_path):
        logging.warning(f"exp_tuple file not found: {exp_tuple_path}")
        return result
    try:
        with open(exp_tuple_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        logging.error(f"failed to read exp_tuple: {e}")
        return result

    if not isinstance(data, dict):
        return result

    # Case A: top-level qid
    # for question_id in data.keys(), e.g., exp_tuple_v0.json
    for k, v in data.items():
        if isinstance(k, str) and _is_question_node(v):
            result[k] = v

    # Case B: episode -> qid
    # structure like experience_output.json (scene_id as outer key), but experience_output.json not have "question" key
    for _, bucket in data.items():
        if isinstance(bucket, dict):
            for qid, qnode in bucket.items():
                if isinstance(qid, str) and _is_question_node(qnode):
                    result[qid] = qnode

    return result


def format_caption_prompt(
    question_text: str,
    captions_by_steps: List[Tuple[str, str, Optional[int], Optional[int]]],  # (step_key, caption, chosen_bvf, chosen_cvf)
    task_outcome: Optional[str] = None,
) -> Tuple[str, List[Tuple[str, str]]]:
    """
    Generate caption for a chunk of steps (每10步的caption生成，和原版完全一样)
    """
    sys_prompt = (
        "You are summarizing a movement trajectory in an indoor environment from step captions. "
        "BASELINE POLICY: the agent first selects a broader direction (BVF) and then a closer sub-direction (CVF) within that BVF. This two-stage selection is a fixed baseline and is NOT to be debated; use the provided chosen BVF/CVF only as internal evidence to understand movement direction. "
        "INPUT: a question and several step captions (what was visible/focused at each step), together with the chosen BVF and CVF indices at each step. "
        "TASK: condense these steps into a clear sequence of where the agent moved or focused in the environment (trajectory), using region/landmark words (e.g., hallway, entrance, kitchen zone, sink area). Do NOT mention or discuss 'BVF', 'CVF', 'view', 'snapshot', 'image', or camera operations in your outputs; avoid step IDs; use natural language. "
        "After summarizing the trajectory, write a Critique paragraph reflecting on the route per the given questions. Finally, print an Abstraction line that repeats the Captions paragraph verbatim."
    )
    sys_prompt += (
        "\nOUTPUT (print exactly in this order):\n"
        "Captions: <ONE single paragraph with 16–20 sentences summarizing the overall trajectory and movement logic derived from the captions; use only region/landmark and path terms; avoid any mention of views/BVF/CVF/images; avoid step IDs; cohesive, non-bulleted prose>\n"
        "Critique: <ONE paragraph addressing: whether choices aimed to explore unseen vs solve immediately; how selections impacted the next steps; how timing in the trajectory shaped impact; how selections influenced final outcome; whether better alternatives existed and why>"
    )

    content: List[Tuple[str, str]] = []
    content.append((f"Question: {question_text or '(unknown)'}",))
    if isinstance(task_outcome, str) and task_outcome.strip():
        content.append((f"Task Outcome: {task_outcome.strip().upper()}",))
    content.append(("Below are the step captions and the chosen indices for each step (for your internal reasoning; do NOT mention BVF/CVF in outputs):",))
    for step_key, cap, bvf, cvf in captions_by_steps:
        if isinstance(cap, str) and cap.strip():
            content.append((f"{step_key} Caption: {cap.strip()}",))
        content.append((f"{step_key} Chosen: BVF {('NA' if bvf is None else str(bvf))}; CVF {('NA' if cvf is None else str(cvf))}",))
    content.append((
        "Now print EXACTLY two blocks in order: (1) Captions paragraph (16–20 sentences), (2) Critique paragraph. Then print Abstraction: <repeat the Captions paragraph verbatim>. Do not add any other headers or lines.",
    ))
    return sys_prompt, content


def format_final_caption_prompt(
    question_text: str,
    chunk_captions: List[str],
    task_outcome: Optional[str] = None,
) -> Tuple[str, List[Tuple[str, str]]]:
    """
    Generate final ultimate caption by combining all chunk captions
    Focus on objective spatial and structural information useful for exploration
    """
    sys_prompt = (
        "You are creating an objective exploration report that describes a complete spatial exploration journey. "
        "Your ONLY task is to provide a factual, detailed description of the exploration path and spatial environment. "
        "Focus EXCLUSIVELY on objective spatial information: room types, structural elements, spatial relationships, movement patterns, and navigational details. "
        "Use precise, factual language to describe spatial configurations and exploration sequences. "
        "Include only information that is useful for spatial navigation and exploration. "
        "Use only region/landmark/path terms (e.g., hallway, entrance, kitchen zone, sink area, living room, bedroom, corridor, doorway, intersection, wall, floor, ceiling, furniture placement). "
        "Do NOT mention 'BVF', 'CVF', 'view', 'snapshot', 'image', camera operations, step IDs, or any technical terms. "
        "Do NOT mention the question, task success/failure, emotions, subjective impressions, smells, sounds, or any non-spatial information. "
        "Do NOT use subjective language, emotional descriptions, or sensory details that are not relevant to spatial navigation. "
        "Create a factual, objective report that captures the complete spatial exploration structure."
    )
    sys_prompt += (
        "\nTHINKING PROCESS (Chain of Thought): "
        "Before writing the final report, you MUST think through each segment step by step: "
        "1. Analyze each segment individually to extract all spatial information "
        "2. Identify the spatial elements, room types, and structural details in each segment "
        "3. Trace the movement patterns and transitions between areas across all segments "
        "4. Map out the complete spatial exploration sequence from start to finish "
        "5. Identify connections and relationships between different spatial elements "
        "6. Consider how each segment contributes to the overall exploration narrative "
        "7. Synthesize all information into a comprehensive spatial understanding "
        "\nOUTPUT REQUIREMENTS: "
        "Write ONE comprehensive paragraph with AT LEAST 30 sentences that: "
        "- Describes the complete exploration path from start to finish using objective spatial terms "
        "- Includes detailed factual environmental descriptions: room types, structural elements, spatial layouts, dimensions, orientations "
        "- Captures movement patterns, transitions between areas, and spatial exploration logic with specific details "
        "- Uses precise, objective language to describe spatial configurations, distances, positions, and relationships "
        "- Focuses purely on spatial and structural information useful for navigation "
        "- Flows logically as a detailed factual exploration report "
        "- Provides extensive objective detail about the complete spatial exploration structure "
        "- Includes specific details about: furniture placement, wall positions, doorway locations, floor plans, spatial boundaries "
        "- Describes object locations, sizes, orientations, and spatial relationships in detail "
        "- Captures precise movement sequences, directional changes, and spatial transitions "
        "- Provides comprehensive coverage of all explored areas with maximum detail"
    )

    content: List[Tuple[str, str]] = []
    content.append(("Below are the exploration trajectory segments that describe different portions of the spatial journey:",))
    for i, caption in enumerate(chunk_captions, 1):
        if isinstance(caption, str) and caption.strip():
            content.append((f"Segment {i}: {caption.strip()}",))
    content.append((
        "Now follow the Chain of Thought process above. First, analyze each segment step by step to extract all spatial information. Then trace the complete exploration sequence and identify all spatial relationships. Finally, create a single, comprehensive exploration report that synthesizes all segments into one detailed, objective description of the complete spatial exploration journey. Focus entirely on factual spatial information, structural elements, and movement patterns. Provide extensive detail about room layouts, furniture positions, spatial relationships, movement sequences, and environmental structures. Write at least 30 sentences that provide comprehensive objective detail about every aspect of the exploration structure, including specific measurements, orientations, distances, and spatial configurations.",
    ))
    return sys_prompt, content


def _split_thinking_and_abstraction(full_text: Optional[str]) -> Tuple[str, str]:
    """
    Split model output into (thinking_process, abstraction_only).
    - thinking_process: everything before the first line starting with 'Abstraction:' or '**Abstraction**:' (case-sensitive for double-asterisk; case-insensitive for the rest handled by explicit checks)
    - abstraction_only: the content after the marker on that line (trimmed), plus any subsequent lines
    If no marker is found, returns (full_text or '', '').
    """
    if not isinstance(full_text, str) or not full_text.strip():
        return "", ""
    lines = [ln.rstrip() for ln in full_text.splitlines()]
    abs_idx = -1
    # Preferred marker: **Abstraction**: (with colon)
    for i, ln in enumerate(lines):
        s = ln.strip()
        if s.startswith("**Abstraction**:"):
            abs_idx = i
            break
    # Accept **Abstraction** (no colon)
    if abs_idx == -1:
        for i, ln in enumerate(lines):
            if ln.strip() == "**Abstraction**":
                abs_idx = i
                break
    # Fallback to plain Abstraction: (with colon, case-insensitive)
    if abs_idx == -1:
        for i, ln in enumerate(lines):
            if ln.strip().lower().startswith("abstraction:"):
                abs_idx = i
                break
    # Accept plain Abstraction (no colon), as a title line
    if abs_idx == -1:
        for i, ln in enumerate(lines):
            if ln.strip().lower() == "abstraction":
                abs_idx = i
                break
    # If still not found, treat entire text as abstraction
    if abs_idx == -1:
        return "", full_text.strip()
    thinking = "\n".join(lines[:abs_idx]).strip()
    abs_line = lines[abs_idx]
    # Take content after the first colon on the marker line (if any). If no colon, drop the title.
    if ":" in abs_line:
        first_part = abs_line.split(":", 1)[1].lstrip()
    else:
        first_part = ""
    tail = "\n".join(lines[abs_idx + 1:]).strip()
    abstraction_only = (first_part + ("\n" + tail if tail else "")).strip()
    return thinking, abstraction_only


def generate_caption_for_question(
    exp_tuple_path: str,
    question_id: str,
    seed: Optional[int] = None,
    max_steps: Optional[int] = None,
) -> Optional[dict]:
    """
    Generate final ultimate caption for a single question by processing its step logs.
    Uses the same chunking logic as the original script (每10步生成caption) then combines all chunks.
    
    Returns a dict: {
      'question_text': str,
      'caption': str,           # Final ultimate caption
      'status': str,            # 'success' or 'fail'
    }
    or None if the question_id is not found.
    """
    qnode = _load_tuple_node(exp_tuple_path, question_id)
    if not isinstance(qnode, dict):
        return None

    question_text, steps = _collect_steps(qnode)
    if not steps:
        return None

    # Prepare step-level captions
    step_pairs: List[Tuple[str, str, Optional[int], Optional[int]]] = []  # (step_key, caption, bvf, cvf)
    for step_key, sd in steps:
        cap = sd.get("Caption") or sd.get("caption") or ""
        bvf = sd.get("chosen_BVF") if isinstance(sd.get("chosen_BVF"), int) else None
        cvf = sd.get("chosen_CVF") if isinstance(sd.get("chosen_CVF"), int) else None
        step_pairs.append((step_key, (cap if isinstance(cap, str) else ""), bvf, cvf))

    # Determine task outcome
    task_outcome = None
    # final_reward = str(qnode.get("final_reward", "")).lower()
    final_reward = str(qnode.get("step_0", {}).get("final_reward", "")).lower()
    if final_reward == "pass":
        task_outcome = "PASS"
    elif final_reward == "fail":
        task_outcome = "FAIL"

    # Step 1: Generate chunk captions (每10步，和原版完全一样)
    chunk_captions: List[str] = []
    group_size = 10  # 每10步一组，和原版一样
    for i in range(0, len(step_pairs), group_size):
        chunk = step_pairs[i : i + group_size]
        logging.info(f"[Chunk] qid={question_id} chunk={i//group_size+1} range_keys={[kp for kp,_1,_2,_3 in chunk]}")
        
        sys_p, cont = format_caption_prompt(
            question_text, chunk, task_outcome=task_outcome
        )
        
        try:
            chunk_out = call_openai_api(sys_p, cont, seed=seed)
            chunk_text = (chunk_out or "").strip()
            
            # Extract only the Captions paragraph from the chunk output
            thinking_process, caption_only = _split_thinking_and_abstraction(chunk_text)
            if caption_only:
                chunk_captions.append(caption_only)
                logging.info(f"[Chunk] qid={question_id} chunk={i//group_size+1} caption_len={len(caption_only)}")
        except Exception as e:
            logging.warning(f"Failed to generate chunk caption for {question_id} chunk {i//group_size+1}: {e}")

    if not chunk_captions:
        logging.warning(f"No chunk captions generated for {question_id}")
        return {
            "question_text": question_text,
            "caption": "",
            "status": "fail",
        }

    # Step 2: Generate final ultimate caption by combining all chunks
    logging.info(f"[Final] qid={question_id} combining {len(chunk_captions)} chunks")
    final_sys, final_cont = format_final_caption_prompt(
        question_text, chunk_captions, task_outcome=task_outcome
    )
    
    try:
        final_out = call_openai_api(final_sys, final_cont, seed=seed)
        final_caption = (final_out or "").strip()
        
        # Determine status based on task outcome
        status = "success" if task_outcome == "PASS" else "fail"
        
        logging.info(f"[Final] qid={question_id} final_caption_len={len(final_caption)} status={status}")
        
        return {
            "question_text": question_text,
            "caption": final_caption,
            "status": status,
        }
    except Exception as e:
        logging.error(f"Failed to generate final caption for {question_id}: {e}")
        return {
            "question_text": question_text,
            "caption": "",
            "status": "fail",
        }


def _write_incremental_json(out_path: str, qid: str, obj: dict):
    """Write a single question result to the output JSON file incrementally."""
    try:
        output_dir = os.path.dirname(out_path)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)
        if os.path.exists(out_path):
            try:
                with open(out_path, "r", encoding="utf-8") as rf:
                    existing = json.load(rf) or {}
            except Exception:
                existing = {}
        else:
            existing = {}
        if not isinstance(existing, dict):
            existing = {}
        existing[qid] = obj
        with open(out_path, "w", encoding="utf-8") as wf:
            json.dump(existing, wf, ensure_ascii=False, indent=2)
        logging.info(f"[Write][incremental] wrote qid={qid} to {out_path}")
    except Exception as e:
        logging.warning(f"[Write][incremental] failed for qid={qid} path={out_path}: {e}")


def _parse_args():
    parser = argparse.ArgumentParser(
        description="Generate captions for questions from exp_tuple json files."
    )
    parser.add_argument(
        "--exp_tuple",
        type=str,
        required=True,
        help="Path to exp_tuple json file (required).",
    )
    parser.add_argument(
        "--question_id",
        type=str,
        required=False,
        default=None,
        help="Target question_id to process. Omit for processing all questions.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Optional chat seed (overrides env VLLM_SEED).",
    )
    parser.add_argument(
        "--max_steps",
        type=int,
        default=None,
        help="Optionally cap the number of steps included (use earliest).",
    )
    parser.add_argument(
        "--out",
        type=str,
        required=True,
        help="Output json file path (required).",
    )
    parser.add_argument(
        "--max_questions",
        type=int,
        default=None,
        help="Optional cap when processing all questions.",
    )
    return parser.parse_args()


def main():
    args = _parse_args()
    logging.basicConfig(level=logging.INFO)

    # Mode 1: single question
    if isinstance(args.question_id, str) and len(args.question_id) > 0:
        result_obj = generate_caption_for_question(
            exp_tuple_path=args.exp_tuple,
            question_id=args.question_id,
            seed=args.seed,
            max_steps=args.max_steps,
        )
        if result_obj is None:
            print("{}")
            return
        print(json.dumps({args.question_id: result_obj}, ensure_ascii=False, indent=2))
        if isinstance(args.out, str) and len(args.out) > 0:
            output_dir = os.path.dirname(args.out)
            if output_dir:
                os.makedirs(output_dir, exist_ok=True)
            with open(args.out, "w", encoding="utf-8") as f:
                json.dump({args.question_id: result_obj}, f, ensure_ascii=False, indent=2)
            logging.info(f"[Write] wrote single question result to {args.out}")
        return

    # Mode 2: process all questions in the file
    all_nodes = load_all_question_nodes(args.exp_tuple)
    if not all_nodes:
        logging.warning("no question nodes found in exp_tuple; nothing to do")
        return

    qids = sorted(all_nodes.keys())
    if isinstance(args.max_questions, int) and args.max_questions > 0:
        qids = qids[: args.max_questions]

    results: Dict[str, dict] = {}
    for qid in qids:
        try:
            obj = generate_caption_for_question(
                exp_tuple_path=args.exp_tuple,
                question_id=qid,
                seed=args.seed,
                max_steps=args.max_steps,
            )
            if obj is None:
                results[qid] = {"question_text": "", "caption": "", "status": "fail"}
            else:
                results[qid] = obj
            # incremental write after each question
            _write_incremental_json(args.out, qid, results[qid])
        except Exception as e:
            logging.warning(f"caption generation failed for {qid}: {e}")
            results[qid] = {"question_text": "", "caption": "", "status": "fail"}
            _write_incremental_json(args.out, qid, results[qid])

    # final write to ensure consistency
    output_dir = os.path.dirname(args.out)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    logging.info(f"[Write] wrote batch results for {len(results)} questions to {args.out}")


if __name__ == "__main__":
    main()
